# Generated by Django 5.2.5 on 2025-09-01 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('prompt', models.TextField(blank=True, default='')),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('info_text', models.TextField(blank=True, default='')),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('current_bid', models.FloatField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.auctionscraperun')),
            ],
        ),
    ]
