# Generated by Django 5.2.5 on 2025-09-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auctionitem_main_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='ends_at',
            field=models.CharField(blank=True, null=True),
        ),
    ]
