# Generated by Django 5.2.5 on 2025-09-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_auctionitem_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='estimate',
            field=models.IntegerField(null=True),
        ),
    ]
